did_django_spoontacular_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views
from .views import LogOut, BusqAle

# 33389
app_name = "main"

urlpatterns = [

    path('', views.index, name="home"),
    path('results', views.results.as_view(), name="results"),
    path('add_to_shopping_list/<int:ingredient_id>/<str:ingredient_name>/', views.add_to_shopping_list,
         name='add_to_shopping_list'),
    path('shopping_list/', views.shopping_list.as_view(), name='shopping_list'),
    path('remove_one_from_shopping_list/<int:ingredient_id>/', views.remove_one_from_shopping_list,
         name='remove_one_from_shopping_list'),
    path('remove_all_from_shopping_list/<int:ingredient_id>/', views.remove_all_from_shopping_list,
         name='remove_all_from_shopping_list'),
    path('recipe_detail/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('registro/', views.RegistroView.as_view(), name='registro'),
    path('login/', views.Login.as_view(), name='login'),
    path('perfil/<int:pk>/', views.PerfilView.as_view(), name='perfil'),
    path('logout/', LogOut.as_view(), name='logout'),
    path('recipe_detail_pdf/<int:recipe_id>', views.recipe_detail_pdf, name='recipe_pdf'),
    path('busqAle/', views.BusqAle.as_view(), name="busq_ale"),
    path('result_ale', views.result_ale.as_view(), name="result_ale")


]

main/models.py
from django.db import models
from django.conf import settings


class Ingredientes(models.Model):
    name = models.CharField(max_length=100)
    count = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.name} ({self.count})"


class Alergenos(models.Model):
    name = models.CharField(max_length=100, unique=True)
    seleccionado = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Perfil(models.Model):
    username = models.ForeignKey(settings.AUTH_USER_MODEL, models.PROTECT)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=254, unique=True)
    usernameSN = models.CharField(max_length=40)
    passwordSN = models.CharField(max_length=40)
    hashSN = models.CharField(max_length=40)
    listaAle = models.ManyToManyField(Alergenos, blank=True)
    listaIng = models.ManyToManyField(Ingredientes, blank=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import transaction

from .models import Perfil, Alergenos
from django.contrib.auth.forms import AuthenticationForm


class RegistroForm(UserCreationForm):
    alergenos = forms.ModelMultipleChoiceField(
        queryset=Alergenos.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email')

    @transaction.atomic()
    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            # Crear el perfil
            user_profile = Perfil.objects.create(
                username=user,
                first_name=self.cleaned_data['first_name'],
                last_name=self.cleaned_data['last_name'],
                email=self.cleaned_data['email']
            )
            # Establecer los alérgenos seleccionados y marcar el campo is_selected como True
            selected_allergens = self.cleaned_data['alergenos']
            for alergeno in selected_allergens:
                alergeno.is_selected = True
                alergeno.save()
            user_profile.listaAle.set(selected_allergens)
            user_profile.save()
        return user


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['password', 'username']

main/views.py
from django.shortcuts import render, reverse, redirect
from django.db import transaction
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic import ListView, CreateView
from .forms import RegistroForm
from .mixins import (APIMixin)
from .models import Ingredientes, Perfil, Alergenos
from .utils import render_to_pdf


'''
Basic view for selecting query
'''


def index(request):
    if request.method == "POST":
        cat = request.POST.get("cat", None)
        query = request.POST.get("query", None)
        if cat and query:
            # Genera la URL con los parámetros cat y query
            url = reverse('main:results') + f'?cat={cat}&query={query}'
            return redirect(url)

    return render(request, 'main/index.html', {})


class results(View):
    def get(self, request):
        cat = request.GET.get("cat", None)
        query = request.GET.get("query", None)

        if cat and query:
            results = APIMixin(cat=cat, query=query).get_data()
            if results:
                user = request.user
                perfil = Perfil.objects.get(username=user)
                alergenos = perfil.listaAle.all()
                alergenos_nombres = [alergeno.name for alergeno in alergenos]

                for result in results:
                    result_name = result.get('name', result.get('title', ''))
                    if any(alergeno in result_name for alergeno in alergenos_nombres):
                        result['color'] = 'red'
                    else:
                        result['color'] = 'green'

                context = {
                    "results": results,
                    "cat": cat,
                    "query": query,
                }
                return render(request, 'main/results.html', context)
        return redirect(reverse('main:home'))


def add_to_shopping_list(request, ingredient_id, ingredient_name):
    try:
        # Obtener el perfil del usuario actual
        perfil, created = Perfil.objects.get_or_create(username=request.user)

        # Obtenemos el ingrediente del perfil del usuario
        ingredient = perfil.listaIng.filter(id=ingredient_id).first()

        if ingredient is not None:
            # Si el ingrediente ya existe en la lista de ingredientes del perfil, aumentamos su cantidad en uno
            ingredient.count += 1
            ingredient.save()
        else:
            # Si el ingrediente no existe en la lista de ingredientes del perfil, lo creamos con una cantidad de uno
            ingredient = Ingredientes.objects.create(id=ingredient_id, name=ingredient_name, count=1)
            perfil.listaIng.add(ingredient)

    except Exception as e:
        # Manejar cualquier otro error que pueda ocurrir
        print(f"Error: {e}")

    # Redireccionamos a la página de la lista de la compra
    return redirect('main:shopping_list')


def remove_one_from_shopping_list(request, ingredient_id):
    try:
        # Obtenemos el perfil del usuario autenticado
        perfil = Perfil.objects.get(username=request.user)

        # Obtenemos el ingrediente específico por su ID
        ingredient = perfil.listaIng.get(id=ingredient_id)

        if ingredient.count > 1:
            # Si el ingrediente tiene más de 1 en el count, reducirlo en 1
            ingredient.count -= 1
            ingredient.save()
        else:
            # Si solo hay 1 o menos, eliminar el ingrediente de la lista
            perfil.listaIng.remove(ingredient)

    except Exception as e:
        # Manejar cualquier otro error que pueda ocurrir
        print(f"Error: {e}")

    # Redirigir a la página de la lista de compras
    return redirect('main:shopping_list')


def remove_all_from_shopping_list(request, ingredient_id):
    try:
        # Obtenemos el perfil del usuario autenticado
        perfil = Perfil.objects.get(username=request.user)

        # Obtenemos el ingrediente de la lista de compras
        ingredient = perfil.listaIng.filter(id=ingredient_id).first()

        if ingredient is not None:
            # Si el ingrediente está en la lista de ingredientes del perfil, lo eliminamos
            perfil.listaIng.remove(ingredient)

    except Exception as e:
        # Manejar cualquier otro error que pueda ocurrir
        print(f"Error: {e}")

    # Redirigir a la página de la lista de compras
    return redirect('main:shopping_list')


def recipe_detail(request, recipe_id):
    api_client = APIMixin()  # Instancia del cliente API

    # Obtenemos la información detallada de la receta
    recipe_info = api_client.get_recipe_information(recipe_id)
    context = {
        "recipe_info": recipe_info
    }
    return render(request, 'main/recipe_detail.html', context)


def recipe_detail_pdf(request, recipe_id):
    api_client = APIMixin()  # Instancia del cliente API

    # Obtenemos la información detallada de la receta
    recipe_info = api_client.get_recipe_information(recipe_id)
    context = {
        "recipe_info": recipe_info
    }

    pdf = render_to_pdf('main/pdf.html', context)

    return HttpResponse(pdf, content_type='application/pdf')


class RegistroView(CreateView):
    form_class = RegistroForm
    template_name = 'main/registro.html'
    success_url = reverse_lazy('main:home')

    @transaction.atomic # Si hay un error durante el registro no se genera ningun perfil
    def get_template_names(self, request=None):
        return [self.template_name]


class Login(View):
    template_name = "login.html"
    form_class = AuthenticationForm

    def get(self, request):
        form = self.form_class()

        return render(request, 'main/login.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                id = user.pk

                return redirect('main:perfil', pk=user.id)

        form = AuthenticationForm()
        return render(request, 'main/login.html', {'form': form})


class shopping_list(LoginRequiredMixin, ListView):
    template_name = 'main/shopping_list.html'
    context_object_name = 'object_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Obtenemos el perfil del usuario actual
        perfil = Perfil.objects.get(username=self.request.user)

        # Obtenemos todos los ingredientes del perfil

        context['ingredients'] = perfil.listaIng.all()

        return context

    def get_queryset(self):
        # Filtra el perfil del usuario actual
        return Perfil.objects.filter(username=self.request.user)


class PerfilView(LoginRequiredMixin, ListView):
    model = Perfil
    template_name = 'main/perfil.html'
    context_object_name = 'object_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        perfil = Perfil.objects.get(username=user)  # Utiliza el nombre real del campo
        context['user'] = user
        context['perfil'] = perfil
        context['alergenos'] = perfil.listaAle.all()
        print(context)
        print(perfil.listaAle.all())
        return context

    def get_queryset(self):
        # Filtra el perfil del usuario actual
        return Perfil.objects.filter(username=self.request.user)


class LogOut(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('main:home'))


class BusqAle(View):

    def get(self, request):

        model = Alergenos
        context = {'alergenos': Alergenos.objects.all().values_list('name', flat=True)}
        return render(request, 'main/busq_ale.html', {'context': context})

    def post(self, request):
            queryAle = request.POST.get("queryAle", None)
            query = request.POST.get("query", None)
            if query and queryAle:
                # Genera la URL con los parámetros cat y query
                url = reverse('main:result_ale') + f'?queryAle={queryAle}&query={query}'
                return redirect(url)

            return render(request, 'main/busq_ale.html', {})


class result_ale(View):
    def get(self, request):
        cat = 'recipes'
        queryAle = request.GET.get("queryAle", None)
        query = request.GET.get("query", None)

        if query and queryAle:
            results = APIMixin(cat=cat, query=query, queryAle=queryAle).get_data()

            if results:
                user = request.user

                for result in results:
                    result_name = result.get('name', result.get('title', ''))

                context = {
                    "results": results,
                    "cat": cat,
                    "query": query,
                }
                return render(request, 'main/result_ale.html', context)
        return redirect(reverse('main:home'))

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main.css' %}"></link>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">


  <!-- This allows us to extend the head scripts in HTML docs that have special requirements-->
  {% block extend_head %}

  {% endblock %}

</head>
<body>
    <ul class="sidenav">
        <li><a class="active" href="{% url 'main:home' %}">Home</a></li>
        <li><a href="{% url 'main:results' %}">Resultados</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'main:busq_ale' %}">Filtro por alergenos</a></li>
            <li><a href="{% url 'main:shopping_list' %}">Lista de la compra</a></li>
            <li><a href="{% url 'main:perfil' pk=user.pk %}">Perfil</a></li>
            <li><a href="{% url 'main:logout' %}">Cerrar sesión</a></li>
        {% else %}
            <li><a href="{% url 'main:login' %}">Login</a></li>
            <li><a href="{% url 'main:registro' %}">Registro</a></li>
        {% endif %}

    </ul>
  <!-- This allows us to extend the nav bar in HTML docs that have special requirements-->
  {% block extend_nav %}

  {% endblock %}

  <div class="div-container">

    {% include 'main/partials/logo.html' %}

    {% block content %}

    {% endblock %}

  </div>


  <!-- This allows us to extend the foot scripts in HTML docs that have special requirements-->
    {% block extend_footer %}

  {% endblock %}
  

</body>
</html>

main/templates/main/busq_ale.html
{% extends 'main/base.html' %}
{% load static %}

{% block extend_head %}

{% endblock %}

{% block extend_nav %}
{% endblock %}


{% block content %}

<h3>Busqueda por Alergenos</h3>

    <div class="container">

        <form method="post">
            {% csrf_token %}
            <select id="queryAle" name="queryAle">
                <option selected value="">Selecciona una categoria</option>
                {% for i in context.alergenos %}
                    <option value="{{ i }}">{{ i }}</option>
                {% endfor %}
            </select>


           <label for="username">Buscar</label>
	       <input type="search" id="query" name="query">
           <button type="submit">Confirmar</button>
        </form>

    </div>


{% endblock %}

{% block extend_footer %}




{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %} 



{% endblock %}


{% block content %}

<h3 id="map">Escaner alergenos</h3>

<div class="container">

	<form id="apiform" method="POST" action="/">
    {% csrf_token %}

    	<label for="username">Selecciona una categoria</label>
    	<select name="cat" id="cat">
    		<option selected value="">Selecciona una categoria</option>
		  	<option value="recipes">Recetas</option>
		  	<option value="ingredients">Ingredientes</option>
		  	<option value="menuItems">Ingredientes Menu</option>
		  	<option value="products">Productos</option>
		</select>
	   
	   <label for="username">Buscar</label>
	   <input type="search" id="query" name="query">

	   

	   <button type="submit">Confirmar</button>
	</form>


</div>


{% endblock %}

{% block extend_footer %}




{% endblock %}

main/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %}



{% endblock %}


{% block content %}

<h3>Escaner alergenos</h3>

<div class="container">
  <h2>Login</h2>
    <form method="post">
    {% csrf_token %}

    {{ form }}
    <input type="submit" value="Login">
    </form>
</div>


{% endblock %}

{% block extend_footer %}




{% endblock %}

main/templates/main/pdf.html
{% load static %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %}



{% endblock %}


{% block content %}

<h3>Escaner alergenos</h3>

<div class="container">
    <h3>Detalles de la Receta</h3>
    {% if recipe_info %}
        <h4>{{ recipe_info.title }}</h4>
        <img src="{{ recipe_info.image }}" alt="{{ recipe_info.title }}">
        <p>Servings: {{ recipe_info.servings }}</p>
        <p>Ready in minutes: {{ recipe_info.readyInMinutes }}</p>
        {{ recipe_info.summary | safe}}
        <h3>Ingredientes:</h3>
        <ul>
            {% for ingredient in recipe_info.extendedIngredients %}
                <li>{{ ingredient.name }} - {{ ingredient.amount }} {{ ingredient.unit }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No se encontraron detalles para esta receta.</p>
    {% endif %}
</div>

{% endblock %}

{% block extend_footer %}




{% endblock %}

main/templates/main/perfil.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<h3>Escaner alergenos</h3>

<div class="container">
  <h2>Perfil</h2>
  <p><strong>Nombre de Usuario:</strong> {{ user.username }}</p>
  <p><strong>Nombre:</strong> {{ user.first_name }}</p>
  <p><strong>Apellidos:</strong> {{ user.last_name }}</p>
  <p><strong>Email:</strong> {{ user.email }}</p>
  <p><strong>Alérgenos:</strong>
    <ul>
       {% for alergeno in alergenos %}
      <li>{{ alergeno.name }}</li>
    {% endfor %}
    </ul>
  </p>
  <a href="{% url 'main:logout' %}"><button>Cerrar sesión</button></a>
</div>
{% endblock %}

main/templates/main/recipe_detail.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %}



{% endblock %}


{% block content %}

<h3>Escaner alergenos</h3>

<div class="container">
    <h3>Detalles de la Receta</h3>
    {% if recipe_info %}
        <h4>{{ recipe_info.title }}</h4>
        <img src="{{ recipe_info.image }}" alt="{{ recipe_info.title }}">
        <p>Servings: {{ recipe_info.servings }}</p>
        <p>Ready in minutes: {{ recipe_info.readyInMinutes }}</p>
        <p>{{ recipe_info.summary }}</p>
        <h3>Ingredientes:</h3>
        <ul>
            {% for ingredient in recipe_info.extendedIngredients %}
                <li>{{ ingredient.name }} - {{ ingredient.amount }} {{ ingredient.unit }}</li>
            {% endfor %}
        </ul>
        <a href="{% url 'main:home' %}">Volver</a>
    {% else %}
        <p>No se encontraron detalles para esta receta.</p>
    {% endif %}
</div>


{% endblock %}

{% block extend_footer %}




{% endblock %}

main/templates/main/registro.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %}



{% endblock %}


{% block content %}

<h3>Escaner alergenos</h3>

<div class="container">
  <h2>Registro</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>
</div>


{% endblock %}

{% block extend_footer %}




{% endblock %}

main/templates/main/result_ale.html
    {% extends 'main/base.html' %}
    {% load static %}

    {% block extend_head %}

    {% endblock %}

    {% block extend_nav %}

    {% endblock %}

    {% block content %}

    <h3 id="map">Escaner alergenos-Resultados</h3>

    <div class="container">

        <h4>Resultados de la api para:</h4>
        <h3>Cat: <em style="color: #9c07b6"><b>"{{ cat }}"</b></em></h3>
        <h3>Query: <em style="color: #9c07b6"><b>"{{ query }}"</b></em></h3>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Imagen</th>
                    {% if cat == "recipes" %}
                        <th>Ver receta</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {% for item in results %}
                <tr>
                    <td>{{ item.id }}</td>
                    {% if item.name %}
                        <td style="color: {{ item.color }};">{{ item.name }}</td>
                    {% else %}
                        <td style="color: {{ item.color }};">{{ item.title }}</td>
                    {% endif %}
                    <td><img src="{{ item.image }}" style="width:auto; height: 125px"></td>
                    {% if cat == "recipes" %}
                    <td><a href="{% url 'main:recipe_detail' item.id %}">Ver receta</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% endblock %}

    {% block extend_footer %}

    {% endblock %}

main/templates/main/results.html
{% extends 'main/base.html' %}
{% load static %}

{% block extend_head %}

{% endblock %}

{% block extend_nav %}

{% endblock %}


{% block content %}

<h3 id="map">Escaner alergenos-Resultados</h3>

<div class="container">

    <h4>Resultados de la api para:</h4>
    <h3>Cat: <em style="color: #9c07b6"><b>"{{ cat }}"</b></em></h3>
    <h3>Query: <em style="color: #9c07b6"><b>"{{ query }}"</b></em></h3>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Imagen</th>
                {% if cat == "ingredients" %}
                    <th>Añadir</th>
                {% endif %}
                {% if cat == "recipes" %}
                    <th>Ver receta</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for item in results %}
            <tr>
                <td>{{ item.id }}</td>
                {% if item.name %}
                    <td>{{ item.name }}</td>
                {% else %}
                    <td>{{ item.title }}</td>
                {% endif %}
                {% if cat == "ingredients" %}
                    <td>No image available</td>

                    <td style="text-align: center; vertical-align: middle;">
                         <a href="{% url 'main:add_to_shopping_list' item.id item.name %}">
                            <i class="fas fa-plus"></i>
                        </a>
                    </td>

                {% else %}
                    <td><img src="{{ item.image }}" style="width:auto; height: 125px"></td>
                {% endif %}
                {% if cat == "recipes" %}
                <td><a href="{% url 'main:recipe_detail' item.id %}">Ver receta</a></td>


                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

{% block extend_footer %}

{% endblock %}

main/templates/main/shopping_list.html
{% extends 'main/base.html' %}
{% load static %}

{% block extend_head %}
<!-- Agrega aquí los enlaces a las hojas de estilo o scripts específicos para esta página si es necesario -->
{% endblock %}

{% block extend_nav %}
<!-- Puedes personalizar la barra de navegación aquí si es necesario -->
{% endblock %}

{% block content %}
    <h1>Lista de la compra</h1>
    <table>
        <thead>
            <tr>
                <th>Ingrediente</th>
                <th>Cantidad</th>
                <th>Eliminar 1</th>
                <th>Eliminar todos</th>
            </tr>
        </thead>
        <tbody>
        {% for ingredient in ingredients %}
            <tr>
                <td>{{ ingredient.name }}</td>
                <td>({{ ingredient.count }})</td>
                <td>
                    <a href="{% url 'main:remove_one_from_shopping_list' ingredient.id %}">
                        <i class="fas fa-minus"></i>
                    </a>
                </td>
                <td>
                    <a href="{% url 'main:remove_all_from_shopping_list' ingredient.id %}">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}